/* CARA MEMBUAT TABEL*/
CREATE TABEL latihan (
ID_SISWA INT(11) PRIMARY KEY AUTO_INCREMENT,
NAMA_LENGKAP VARCHAR(255),
NIS CHAR(10),
JK CHAR(1),
TANGGAL_LAHIR DATE,
TEMPAT_LAHIR TEXT,
KELAS VARCHAR(15),
TANGGAL_ENTRI DATETIME
);


/* INSERT DATA */
INSERT INTO latihan SET

ID_SISWA = NULL,
NAMA_LENGKAP ='ANDRIANA',
NIS ='11700059',
JK ='L',
TEMPAT_LAHIR ='SUBANG',
TANGGAL_LAHIR ='2002-06-14',
KELAS ='11 BDP 3',
TANGGAL_ENTRI = NOW;


/* MENAMPILKAN DATA DENGAN KONDISI PEREMPUAN */
SELECT*FROM latihan WHERE JK = 'P'

/* MENAMPILKAN DATA TIDAK LAHIR DI SUBANG */
SELECT*FROM latihan WHERE NOT Tempat_Lahir = 'SUBANG';

/* TAMPILKAN KELAS 12 */
SELECT*FROM latihan WHERE Kelas=12;

/* URUTKAN PALING TUA */
SELECT*FROM latihan order by Tanggal_Lahir ASC;

/* MENAMPILKAN JK = P LAHIR = BOGOR */
SELECT*FROM latihan WHERE JK = 'P' and Tempat_Lahir = 'BOGOR';

/* LAHIR PADA BULAN = JUNI */
SELECT*FROM latihan WHERE MONTH (TANGGAL_LAHIR) = '06'; 

/* UPDATE LAHIR CUCU DI BOGOR */
UPDATE latihan SET TEMPAT_LAHIR = 'BOGOR' WHERE ID_SISWA ='3';

/* DELETE DATA ATAS NAMA DAFFA */
DELETE FROM latihan WHERE ID_SISWA ='4'; 
